# Generated by Django 6.0 on 2025-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
