# Generated by Django 6.0 on 2026-01-09 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0005_invitationdata_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=20)),
                ('wa', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('view_at', models.DateTimeField(blank=True, null=True)),
                ('is_clicked_atm', models.BooleanField(default=False)),
                ('rsvp', models.CharField(blank=True, max_length=50, null=True)),
                ('pax_request', models.PositiveIntegerField(blank=True, null=True)),
                ('pax_confirmed', models.PositiveIntegerField(blank=True, null=True)),
                ('greetings', models.JSONField(default=list)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitationdata')),
            ],
        ),
    ]
