# Generated by Django 6.0 on 2025-12-20 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('groom_name', models.CharField(max_length=200)),
                ('bridal_name', models.CharField(max_length=200)),
                ('dad_groom_name', models.CharField(max_length=200)),
                ('mom_groom_name', models.CharField(max_length=200)),
                ('dad_bridal_name', models.CharField(max_length=200)),
                ('mom_bridal_name', models.CharField(max_length=200)),
                ('sentence_opening', models.TextField()),
                ('sentence_greeting', models.TextField()),
                ('sentence_middlehook', models.TextField()),
                ('sentence_closing', models.TextField()),
                ('img_cover', models.CharField(max_length=500)),
                ('img_groom', models.CharField(max_length=500)),
                ('img_bridal', models.CharField(max_length=500)),
                ('img_gallery', models.JSONField(default=list)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.song')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.template')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('gmaps_link', models.URLField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('time_end', models.CharField(max_length=50)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitations.invitationdata')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=200)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_gifts', to='invitations.invitationdata')),
            ],
        ),
    ]
