# Generated by Django 6.0 on 2025-12-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_song_path'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationdata',
            name='img_bridal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='img_cover',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='img_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='img_groom',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.song'),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.template'),
        ),
    ]
