# Generated by Django 6.0 on 2026-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_invitationdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationdata',
            name='img_bridal',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='img_cover',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='img_groom',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='sentence_closing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='sentence_greeting',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='sentence_middlehook',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitationdata',
            name='sentence_opening',
            field=models.TextField(blank=True, default=''),
        ),
    ]
