# Generated by Django 6.0 on 2026-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitationdata_img_bridal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationdata',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
