# Generated by Django 6.0 on 2026-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_backfill_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationticket',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
