# Generated by Django 6.0 on 2026-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_invitationticket_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_main_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitationdata',
            name='bridal_fullname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invitationdata',
            name='groom_fullname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invitationdata',
            name='sentence_digital_gift',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invitationdata',
            name='sentence_love_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invitationdata',
            name='sentence_rsvp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
